name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:
    name: test (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff build
          # Dependencias del proyecto (si las hubiera)
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Run unit tests (unittest)
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v

      - name: Build (sdist + wheel)
        run: |
          python -m build
        # Publica los artefactos de build para inspección
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*
